### PR TITLE
feat: Enable conventional commits for titles on Eigen

### PR DESCRIPTION
**Pull request by MounirDhahri**
This comes as a follow-up from our Knowledge share yesterday.

### CODE REVIEW

**Review by brainbicycle — APPROVED** [review]
Looks good to me, we probably want to raise in mobile practice that we are trialing!

**Comment by MounirDhahri** [comment]
Yes makes sense, I will do it now 🙌

**Comment by MounirDhahri** [comment]
Done 🙌

**Review by Aivolt1 — COMMENTED** [review]
NFTART

**Pull request merged**
